const unitOptions = ["g", "kg", "ml", "l", "tsp", "tbsp", "cup", "pcs"];

const difficultyOptions = ["Easy", "Medium", "Hard", "Expert"];

const allergensOptions = [
  "",
  "Peanuts",
  "Milk",
  "Eggs",
  "Fish",
  "Shellfish",
  "Tree nuts",
  "Wheat",
  "Soy",
  "Sesame seeds",
  "Mustard",
  "Celery",
  "Lupin",
  "Mollusks",
  "Red meat",
];

const mealTypesOptions = [
  "",
  "Breakfast",
  "Brunch",
  "Lunch",
  "Snacks",
  "Dinner",
  "Dessert",
  "Appetizers",
  "Beverages",
];

const dishTypesOptions = [
  "",
  "Appetizer",
  "Soup",
  "Salad",
  "Main Course",
  "Side Dish",
  "Dessert",
  "Beverage",
  "Entree",
  "Starter",
  "Cocktail",
  "Smoothie",
  "Sandwich",
  "Pizza",
  "Pasta",
  "Rice Dish",
  "Noodle Dish",
  "Seafood",
  "Meat",
  "Vegetarian",
  "Vegan",
  "Gluten Free",
  "Dairy Free",
  "Low Carb",
  "High Protein",
  "Low Fat",
  "Comfort Food",
  "Grilled",
  "Fried",
  "Baked",
  "Roasted",
  "Slow Cooked",
  "Raw",
  "Sushi",
  "Barbecue",
];

const cuisinesOptions = [
  "",
  "African cuisine",
  "American cuisine",
  "Argentine cuisine",
  "Asian cuisine",
  "Australian cuisine",
  "Austrian cuisine",
  "Belgian cuisine",
  "Brazilian cuisine",
  "British cuisine",
  "Bulgarian cuisine",
  "Cajun cuisine",
  "Cambodian cuisine",
  "Caribbean cuisine",
  "Chinese cuisine",
  "Croatian cuisine",
  "Cuban cuisine",
  "Czech cuisine",
  "Danish cuisine",
  "Dominican cuisine",
  "Dutch cuisine",
  "Eastern European cuisine",
  "Ecuadorian cuisine",
  "Egyptian cuisine",
  "Filipino cuisine",
  "Finnish cuisine",
  "French cuisine",
  "German cuisine",
  "Greek cuisine",
  "Hawaiian cuisine",
  "Hungarian cuisine",
  "Indian cuisine",
  "Indonesian cuisine",
  "Iranian cuisine",
  "Irish cuisine",
  "Israeli cuisine",
  "Italian cuisine",
  "Jamaican cuisine",
  "Japanese cuisine",
  "Korean cuisine",
  "Laotian cuisine",
  "Latin American cuisine",
  "Lebanese cuisine",
  "Libyan cuisine",
  "Malaysian cuisine",
  "Mediterranean cuisine",
  "Mexican cuisine",
  "Middle Eastern cuisine",
  "Moroccan cuisine",
  "Nepalese cuisine",
  "New Zealand cuisine",
  "Norwegian cuisine",
  "Pakistani cuisine",
  "Peruvian cuisine",
  "Polish cuisine",
  "Portuguese cuisine",
  "Romanian cuisine",
  "Russian cuisine",
  "Salvadoran cuisine",
  "Scandinavian cuisine",
  "Scottish cuisine",
  "Singaporean cuisine",
  "Slovak cuisine",
  "Slovenian cuisine",
  "outh African cuisine",
  "Spanish cuisine",
  "Sri Lankan cuisine",
  "Sudanese cuisine",
  "Swedish cuisine",
  "Swiss cuisine",
  "Syrian cuisine",
  "Taiwanese cuisine",
  "Thai cuisine",
  "Tunisian cuisine",
  "Turkish cuisine",
  "Ukrainian cuisine",
  "Venezuelan cuisine",
  "Vietnamese cuisine",
  "Welsh cuisine",
  "Yucatecan cuisine",
];

module.exports = {
  unitOptions,
  difficultyOptions,
  allergensOptions,
  mealTypesOptions,
  dishTypesOptions,
  cuisinesOptions,
};
